# domain source files / params
geojson:
  watershed : '../data/HUC_12.geojson'
  springshed : '../data/Bear_Springshed.geojson'
  creeks : '../data/creeks_geoJSON.geojson'
  subdomain : '../../src/data/mf6_modelData/creek_subdomain.geojson'
csv:
  karst_features : '../data/karst_features.csv'
  sinkholes : '../data/bear_sinkholes_coords.txt'
  precip : '../data/BS_precip_5_1_24_5_30_24.csv'
DEM : '../../src/data/DEM/dem_1m_m.bil'
crs : 'EPSG:32615'

# grid discretization params

delr : 5
delc : 5
top_config : 'DEM'
lenuni : 2 #m 
botm : 
  - layer : 0 #bottommost layer is 0 then numbering goes up.
    layer_type : 'constant_slope' #constant_elev, constant_slope, custom
    azimuth : 298.07 #degrees
    dip : 0.58 #degrees
    max_elev : 325.044 # top of decorah shale
    # min_elev :  
  - layer : 1
    layer_type : 'constant_slope' #constant_elev, constant_slope, custom
    azimuth : 298.07
    dip : 0.58
    max_elev : 383 #to represent possible conduit activation at higher elevations. based on observational data

#time discretization
tuni : 'DAYS'
nper : 1 #The number of stress periods
nstp : 1 #The number of timesteps
perlen : 1.0 #The length of each stress period
tsmult : 1.0 #length of successive timesteps

#aquifer params
Kh: #horizontal K, 1 for each layer
  - 1.3 #m/d
  - 2.6 #m/d TODO: calibrate this value 
Kv : #vertical K
  - 1.3
  - 2.6
# TO DO: Conduit conductivities
# Kcond : #TODO configure for multiple variable conductivities
#   h : 
#   v : 
# KBPP : #


