name: simple_test
description: ''
creation_date: 2026/05/27 15:59
pykasso_version: 1.0.1
grid:
  x0: 557546.0
  y0: 4867231.0
  z0: 370.0
  nx: 588
  ny: 475
  nz: 6
  dx: 5.0
  dy: 5.0
  dz: 5.0
core:
  locations:
    root: c:\Users\huan1428\Documents\karst\UMNBearSpring\openkarst\conduits
    project: c:\Users\huan1428\Documents\karst\UMNBearSpring\openkarst\conduits/simple_test/
  paths:
    project_dir: simple_test/
    inputs_dir: simple_test/inputs/
    outputs_dir: simple_test/outputs/
  filenames:
    parameters: parameters.yaml
    project: project.yaml
    log: project.log
n_simulations: 1
simulations:
- simple_test/outputs/simulation_1/
